package hib;
// Generated May 14, 2014 11:33:34 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private int idCategory;
     private String catName;
     private Set<ItemHasCategory> itemHasCategories = new HashSet<ItemHasCategory>(0);
     private Set<Type> types = new HashSet<Type>(0);
     private Set<Model> models = new HashSet<Model>(0);

    public Category() {
    }

	
    public Category(int idCategory) {
        this.idCategory = idCategory;
    }
    public Category(int idCategory, String catName, Set<ItemHasCategory> itemHasCategories, Set<Type> types, Set<Model> models) {
       this.idCategory = idCategory;
       this.catName = catName;
       this.itemHasCategories = itemHasCategories;
       this.types = types;
       this.models = models;
    }
   
    public int getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(int idCategory) {
        this.idCategory = idCategory;
    }
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }
    public Set<ItemHasCategory> getItemHasCategories() {
        return this.itemHasCategories;
    }
    
    public void setItemHasCategories(Set<ItemHasCategory> itemHasCategories) {
        this.itemHasCategories = itemHasCategories;
    }
    public Set<Type> getTypes() {
        return this.types;
    }
    
    public void setTypes(Set<Type> types) {
        this.types = types;
    }
    public Set<Model> getModels() {
        return this.models;
    }
    
    public void setModels(Set<Model> models) {
        this.models = models;
    }




}


