package hib;
// Generated May 14, 2014 11:33:34 PM by Hibernate Tools 3.6.0



/**
 * ItemHasCategory generated by hbm2java
 */
public class ItemHasCategory  implements java.io.Serializable {


     private int IHsCatId;
     private Category category;
     private Suppliers suppliers;
     private Type type;
     private Manufacture manufacture;
     private Item item;
     private Model model;
     private String price;
     private String color;
     private String qty;

    public ItemHasCategory() {
    }

	
    public ItemHasCategory(int IHsCatId, Category category, Suppliers suppliers, Type type, Manufacture manufacture, Item item) {
        this.IHsCatId = IHsCatId;
        this.category = category;
        this.suppliers = suppliers;
        this.type = type;
        this.manufacture = manufacture;
        this.item = item;
    }
    public ItemHasCategory(int IHsCatId, Category category, Suppliers suppliers, Type type, Manufacture manufacture, Item item, Model model, String price, String color, String qty) {
       this.IHsCatId = IHsCatId;
       this.category = category;
       this.suppliers = suppliers;
       this.type = type;
       this.manufacture = manufacture;
       this.item = item;
       this.model = model;
       this.price = price;
       this.color = color;
       this.qty = qty;
    }
   
    public int getIHsCatId() {
        return this.IHsCatId;
    }
    
    public void setIHsCatId(int IHsCatId) {
        this.IHsCatId = IHsCatId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Suppliers getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Suppliers suppliers) {
        this.suppliers = suppliers;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public Manufacture getManufacture() {
        return this.manufacture;
    }
    
    public void setManufacture(Manufacture manufacture) {
        this.manufacture = manufacture;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Model getModel() {
        return this.model;
    }
    
    public void setModel(Model model) {
        this.model = model;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getQty() {
        return this.qty;
    }
    
    public void setQty(String qty) {
        this.qty = qty;
    }




}


