package hib;
// Generated May 14, 2014 11:33:34 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private int idItem;
     private String itName;
     private String itColor;
     private Set<ItemHasCategory> itemHasCategories = new HashSet<ItemHasCategory>(0);

    public Item() {
    }

	
    public Item(int idItem) {
        this.idItem = idItem;
    }
    public Item(int idItem, String itName, String itColor, Set<ItemHasCategory> itemHasCategories) {
       this.idItem = idItem;
       this.itName = itName;
       this.itColor = itColor;
       this.itemHasCategories = itemHasCategories;
    }
   
    public int getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(int idItem) {
        this.idItem = idItem;
    }
    public String getItName() {
        return this.itName;
    }
    
    public void setItName(String itName) {
        this.itName = itName;
    }
    public String getItColor() {
        return this.itColor;
    }
    
    public void setItColor(String itColor) {
        this.itColor = itColor;
    }
    public Set<ItemHasCategory> getItemHasCategories() {
        return this.itemHasCategories;
    }
    
    public void setItemHasCategories(Set<ItemHasCategory> itemHasCategories) {
        this.itemHasCategories = itemHasCategories;
    }




}


