package hib;
// Generated May 14, 2014 11:33:34 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Manufacture generated by hbm2java
 */
public class Manufacture  implements java.io.Serializable {


     private int idManufc;
     private String manufName;
     private Set<ItemHasCategory> itemHasCategories = new HashSet<ItemHasCategory>(0);

    public Manufacture() {
    }

	
    public Manufacture(int idManufc) {
        this.idManufc = idManufc;
    }
    public Manufacture(int idManufc, String manufName, Set<ItemHasCategory> itemHasCategories) {
       this.idManufc = idManufc;
       this.manufName = manufName;
       this.itemHasCategories = itemHasCategories;
    }
   
    public int getIdManufc() {
        return this.idManufc;
    }
    
    public void setIdManufc(int idManufc) {
        this.idManufc = idManufc;
    }
    public String getManufName() {
        return this.manufName;
    }
    
    public void setManufName(String manufName) {
        this.manufName = manufName;
    }
    public Set<ItemHasCategory> getItemHasCategories() {
        return this.itemHasCategories;
    }
    
    public void setItemHasCategories(Set<ItemHasCategory> itemHasCategories) {
        this.itemHasCategories = itemHasCategories;
    }




}


