package hib;
// Generated May 14, 2014 11:33:34 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Model generated by hbm2java
 */
public class Model  implements java.io.Serializable {


     private int idModel;
     private Type type;
     private Category category;
     private String modName;
     private Set<ItemHasCategory> itemHasCategories = new HashSet<ItemHasCategory>(0);

    public Model() {
    }

	
    public Model(int idModel, Type type, Category category) {
        this.idModel = idModel;
        this.type = type;
        this.category = category;
    }
    public Model(int idModel, Type type, Category category, String modName, Set<ItemHasCategory> itemHasCategories) {
       this.idModel = idModel;
       this.type = type;
       this.category = category;
       this.modName = modName;
       this.itemHasCategories = itemHasCategories;
    }
   
    public int getIdModel() {
        return this.idModel;
    }
    
    public void setIdModel(int idModel) {
        this.idModel = idModel;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getModName() {
        return this.modName;
    }
    
    public void setModName(String modName) {
        this.modName = modName;
    }
    public Set<ItemHasCategory> getItemHasCategories() {
        return this.itemHasCategories;
    }
    
    public void setItemHasCategories(Set<ItemHasCategory> itemHasCategories) {
        this.itemHasCategories = itemHasCategories;
    }




}


